name: Generate Snake Game from GitHub Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: output
          fetch-depth: 0

      - name: Generate snake animation
        uses: Platane/snk@v3.5.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: generate snake animation"
          add: "dist/"